### ISSUE TITLE
StyleCop and compiler warnings

### ISSUE THREAD

**Issue by stuartwhiteford** [MelGrubb/BuilderGenerator#12]
Hi,

Would it be possible to adjust the generated code to have StyleCop ignore the generated files?

Something like...

```
// <auto-generated/>
#pragma warning disable
```

and

```
#pragma warning restore
```

Happy to submit a PR with the changes...?
Cheers,
Stuart.

**Comment by MelGrubb** [comment]
Since the filenames already include "generated", I would have thought that StyleCop was supposed to be ignoring them already. Interesting. I don't think I'd want to turn off _all_ the warnings, but I also can't predict what your StyleCop configuration will look like, so maybe this is the only option. I'm still wondering why it's complaining about a generated file in the first place though.

**Comment by MelGrubb** [comment]
I'm hopefully back to active development here soon. If you beat me to it I'm happy to take a PR though.

**Comment by MelGrubb** [comment]
The generated files now have an "// <auto-generated>" header. I don't see a way to use pragmas to disable ALL warnings. I could be looking in the wrong place, of course, but what I'm seeing says you can't do that.
