### ISSUE TITLE
What version is the latest stable?

### ISSUE THREAD

**Issue by dinotom** [MelGrubb/BuilderGenerator#6]
On Installing the package with either the console or package manager results in version 0.5 being installed. But with that version installed ( at least in VS 2022 RC1) the attribute [GenerateBuilder] is NOT recognized.

I went back to 1.5 and decorated three classes in my Domain project with the [GenerateBuilder] attribute (which is recognized with that version installed) but on Build, nothing is generated

**Comment by dinotom** [comment]
BTW... Great course and presentation on automated testing on Pluralsight. You should do another.

**Comment by MelGrubb** [comment]
Well, so much for notifications working. Sorry I didn't see this earlier. I would love to do another course, specifically one on source generators. We'll see what they say. Let me look into your other question. I sort of stopped working on this while I waited for the tooling to stabilize a little more, but I should be able to get back to it soon. It does appear that NuGet.org is still serving v0.5. Let me see if I can get v1.1 up there for you.

**Comment by MelGrubb** [comment]
I just pushed v1.1.0 to NuGet. I think what happened here is a simple version numbering problem. My publish script was still using v0.5.0. The contents may have been correct though. When I last worked on this, I was trying to get GitHub actions in place to do the publishing for me, and I think that's where it all went wrong. Anyway, I manually pushed v1.1.0 just now, so you should be all caught up. I'm about to dive back into this as my primary side project away from work in order to see whether Visual Studio's support has gotten any better in the last few months. That was the major stumbling block at the time.

**Comment by dinotom** [comment]
I’ll try it later when I’m home thank you for doing it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MelGrubb** [comment]
I could only get it to work locally, but the version coming from NuGet.org was giving me errors. I've de-listed it and re-opened this issue until I can work out what's happened and get a stable version up that I'm happy with. For now, consider 0.5.0 to be the latest stable version. It works, without some of the flexibility I was planning. I just need to figure out what I broke in the last set of updates and get it all back on straight, then I'll be back to getting it in line with where the roadmap said it should be.

**Comment by MelGrubb** [comment]
Okay, got it. I burned a couple numbers in the process, so I'm having to call it v1.2.0 now. NuGet won't let you reuse numbers... ever, and I made some actual changes along the way, so we'll call it 1.2 and just change the roadmap to move some things to v1.5. Tests are passing again, so I'm re-closing the issue.
